-- MySQL Script generated by MySQL Workbench
-- Sat 22 Feb 2020 16:34:03 GMT
-- Model: DumLi Wire Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wire
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attachment` ;
DROP TABLE IF EXISTS `message` ;
DROP TABLE IF EXISTS `participant` ;
DROP TABLE IF EXISTS `room` ;
DROP TABLE IF EXISTS `account` ;
DROP TABLE IF EXISTS `user` ;
