SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `token`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `token` (
  `token` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`token`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE IF NOT EXISTS `subnet` (
  `netaddr` UNSIGNED INT NOT NULL,
  `mask` UNSIGNED INT NOT NULL,
  `idvpc` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) DEFAULT ""
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`subnet`, `mask`))
  CONSTRAINT `fk_subnet_vpc`
    FOREIGN KEY (`idvpc`)
    REFERENCES `vpc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


CREATE TABLE IF NOT EXISTS `vpc` (
  `id` VARCHAR(255) NOT NULL,
  `idsection` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) DEFAULT ""
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
  CONSTRAINT `fk_vpc_section`
    FOREIGN KEY (`idsection`)
    REFERENCES `section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE IF NOT EXISTS `section` (
  `id` VARCHAR(255) NOT NULL,
  `parent` VARCHAR(255),
  `description` VARCHAR(255) DEFAULT ""
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
  CONSTRAINT `fk_section_section`
    FOREIGN KEY (`parent`)
    REFERENCES `section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
